name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy Job Scraper Frontend
        run: |
          ~/scripts/deploy-job-scraper-frontend-prod.sh
